auto: true
permalink: /:title
markdown: rdiscount

author: <a href="http://lelouchhe.github.com/about.html">LelouchHe</a>
copyright: By <a href="http://lelouchhe.github.com/about.html">LelouchHe</a> &copy; Copyright 2012
